=== gotthardp/python-mercuryapi/mercuryapi-1.35.2.72/c/src/api/lib/LTK/Definitions/llrpdef.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 -
 -  Copyright 2007 Impinj Inc.
 -
 -  Licensed under the Apache License, Version 2.0 (the "License");
 -  you may not use this file except in compliance with the License.
 -  You may obtain a copy of the License at
 -
 -       http://www.apache.org/licenses/LICENSE-2.0
 -
 -  Unless required by applicable law or agreed to in writing, software
 -  distributed under the License is distributed on an "AS IS" BASIS,
 -  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 -  See the License for the specific language governing permissions and
 -  limitations under the License.
 -                                                                           -
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 -->

<xs:schema
  targetNamespace="http://www.llrp.org/ltk/schema/core/encoding/binary/1.0"
  xmlns:llrpdef="http://www.llrp.org/ltk/schema/core/encoding/binary/1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  version="1.0">

  <xs:annotation>
    <xs:documentation xml:lang="en">
	Copyright 2007 Impinj Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	     http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="llrpdef" type="llrpdef:llrpDefinition"/>

  <xs:complexType name="llrpDefinition">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="messageDefinition"
                  type="llrpdef:messageDefinition"/>
      <xs:element name="parameterDefinition"
                  type="llrpdef:parameterDefinition"/>
      <xs:element name="choiceDefinition"
                  type="llrpdef:choiceDefinition"/>
      <xs:element name="enumerationDefinition"
                  type="llrpdef:enumerationDefinition"/>
      <xs:element name="vendorDefinition"
                  type="llrpdef:vendorDefinition"/>
      <xs:element name="namespaceDefinition"
                  type="llrpdef:namespaceDefinition"/>
      <xs:element name="customMessageDefinition"
                  type="llrpdef:customMessageDefinition"/>
      <xs:element name="customParameterDefinition"
                  type="llrpdef:customParameterDefinition"/>
      <xs:element name="customChoiceDefinition"
                  type="llrpdef:customChoiceDefinition"/>
      <xs:element name="customEnumerationDefinition"
                  type="llrpdef:customEnumerationDefinition"/>
      <xs:element name="annotation" type="llrpdef:annotation"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="messageDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="field"     type="llrpdef:fieldDefinition"/>
        <xs:element name="reserved"  type="llrpdef:reservedDefinition"/>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="parameter" type="llrpdef:parameterReference"/>
        <xs:element name="choice"    type="llrpdef:choiceReference"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"           type="llrpdef:name"    use="required"/>
    <xs:attribute name="typeNum"        type="llrpdef:typeNum" use="required"/>
    <xs:attribute name="required"       type="xs:boolean"      use="optional"/>
    <xs:attribute name="responseType"   type="llrpdef:name"    use="optional"/>
  </xs:complexType>

  <xs:complexType name="parameterDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="field"     type="llrpdef:fieldDefinition"/>
        <xs:element name="reserved"  type="llrpdef:reservedDefinition"/>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="parameter" type="llrpdef:parameterReference"/>
        <xs:element name="choice"    type="llrpdef:choiceReference"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"           type="llrpdef:name"    use="required"/>
    <xs:attribute name="typeNum"        type="llrpdef:typeNum" use="required"/>
    <xs:attribute name="required"       type="xs:boolean"      use="optional"/>
  </xs:complexType>

  <xs:complexType name="choiceDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="parameter" type="llrpdef:choiceParameterReference"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="llrpdef:name"    use="required"/>
  </xs:complexType>

  <xs:complexType name="enumerationDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="entry" type="llrpdef:enumerationEntryDefinition"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="llrpdef:name"    use="required"/>
  </xs:complexType>

  <xs:complexType name="enumerationEntryDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="llrpdef:name"    use="required"/>
    <xs:attribute name="value"   type="xs:integer"      use="required"/>
  </xs:complexType>

  <xs:complexType name="vendorDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"       type="llrpdef:name"     use="required"/>
    <xs:attribute name="vendorID"   type="xs:unsignedInt"   use="required"/>
  </xs:complexType>

  <xs:complexType name="namespaceDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="prefix"         type="llrpdef:name" use="required"/>
    <xs:attribute name="URI"            type="xs:anyURI"    use="required"/>
    <xs:attribute name="schemaLocation" type="xs:anyURI"    use="optional"/>
  </xs:complexType>

  <xs:complexType name="customMessageDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="field" type="llrpdef:fieldDefinition"/>
        <xs:element name="reserved" type="llrpdef:reservedDefinition"/>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="parameter" type="llrpdef:parameterReference"/>
        <xs:element name="choice"    type="llrpdef:choiceReference"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"         type="llrpdef:name"    use="required"/>
    <xs:attribute name="vendor"       type="llrpdef:name"    use="required"/>
    <xs:attribute name="subtype"      type="llrpdef:customMessageSubtype" use="required"/>
    <xs:attribute name="namespace"    type="llrpdef:name"    use="required"/>
    <xs:attribute name="responseType" type="llrpdef:name"    use="optional"/>
  </xs:complexType>

  <xs:complexType name="customParameterDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="field"     type="llrpdef:fieldDefinition"/>
        <xs:element name="reserved"  type="llrpdef:reservedDefinition"/>
      </xs:choice>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="parameter" type="llrpdef:parameterReference"/>
        <xs:element name="choice"    type="llrpdef:choiceReference"/>
      </xs:choice>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="allowedIn"
                        type="llrpdef:allowedInParameterReference"/>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="name"       type="llrpdef:name"     use="required"/>
    <xs:attribute name="vendor"     type="llrpdef:name"     use="required"/>
    <xs:attribute name="subtype"    type="xs:unsignedInt"   use="required"/>
    <xs:attribute name="namespace"  type="llrpdef:name"     use="required"/>
  </xs:complexType>

  <xs:complexType name="customChoiceDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="parameter" type="llrpdef:choiceParameterReference"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"       type="llrpdef:name"     use="required"/>
    <xs:attribute name="namespace"  type="llrpdef:name"     use="required"/>
  </xs:complexType>

  <xs:complexType name="customEnumerationDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="entry" type="llrpdef:enumerationEntryDefinition"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"       type="llrpdef:name"     use="required"/>
    <xs:attribute name="namespace"  type="llrpdef:name"     use="required"/>
  </xs:complexType>

  <xs:complexType name="parameterReference">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type"           type="llrpdef:name"    use="required"/>
    <xs:attribute name="repeat"         type="llrpdef:repeat"  use="required"/>
    <xs:attribute name="name"           type="llrpdef:name"    use="optional"/>
  </xs:complexType>

  <xs:complexType name="choiceReference">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type"   type="llrpdef:name"     use="required"/>
    <xs:attribute name="repeat" type="llrpdef:repeat"   use="required"/>
    <xs:attribute name="name"   type="llrpdef:name"     use="optional"/>
  </xs:complexType>

  <xs:complexType name="choiceParameterReference">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type"   type="llrpdef:name"     use="required"/>
  </xs:complexType>

  <xs:complexType name="allowedInParameterReference">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type"   type="llrpdef:name"     use="required"/>
    <xs:attribute name="repeat" type="llrpdef:allowedInRepeat"
                                            default="0-N" use="optional"/>
    <xs:attribute name="name"   type="llrpdef:name"     use="optional"/>
  </xs:complexType>

  <xs:complexType name="fieldDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"   type="llrpdef:name"     use="required"/>
    <xs:attribute name="type"   type="llrpdef:fieldType" use="required"/>
    <xs:attribute name="enumeration" type="llrpdef:name" use="optional"/>
    <xs:attribute name="format" type="llrpdef:fieldFormat" use="optional"/>
  </xs:complexType>

  <xs:complexType name="reservedDefinition">
    <xs:sequence>
      <xs:element name="annotation" type="llrpdef:annotation" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="bitCount" type="llrpdef:reservedBitCount"
                   use="required"/>
  </xs:complexType>

  <xs:complexType name="annotation">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="documentation" type="llrpdef:documentation"/>
      <xs:element name="description" type="llrpdef:description"/>
    </xs:choice>
    <xs:attribute name="source" type="xs:anyURI" use="optional"/>
  </xs:complexType>

  <xs:complexType name="documentation" mixed="true">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="description" mixed="true">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any namespace="http://www.w3.org/1999/xhtml"
            processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="copyright" type="xs:string"/> 
  </xs:complexType>

  <xs:simpleType name="name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z_][a-zA-Z_0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeNum">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="1023"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="repeat">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1"/>
      <xs:enumeration value="0-1"/>
      <xs:enumeration value="0-N"/>
      <xs:enumeration value="1-N"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="allowedInRepeat">
    <xs:restriction base="xs:string">
      <xs:enumeration value="0-1"/>
      <xs:enumeration value="0-N"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="reservedBitCount">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="32"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Custom message subtype 255 is reserved by LTK for later expansion -->
  <xs:simpleType name="customMessageSubtype">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="254"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fieldType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="u1"/>
      <xs:enumeration value="u2"/>

      <xs:enumeration value="u1v"/>

      <xs:enumeration value="u8"/>
      <xs:enumeration value="s8"/>
      <xs:enumeration value="u8v"/>
      <xs:enumeration value="s8v"/>

      <xs:enumeration value="utf8v"/>

      <xs:enumeration value="u16"/>
      <xs:enumeration value="s16"/>
      <xs:enumeration value="u16v"/>
      <xs:enumeration value="s16v"/>

      <xs:enumeration value="u32"/>
      <xs:enumeration value="s32"/>
      <xs:enumeration value="u32v"/>
      <xs:enumeration value="s32v"/>

      <xs:enumeration value="u64"/>
      <xs:enumeration value="s64"/>
      <xs:enumeration value="u64v"/>
      <xs:enumeration value="s64v"/>

      <xs:enumeration value="u96"/>

      <xs:enumeration value="bytesToEnd"/>

    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fieldFormat">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dec"/>
      <xs:enumeration value="Hex"/>
      <xs:enumeration value="Datetime"/>
      <xs:enumeration value="UTF8"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== gotthardp/python-mercuryapi/mercuryapi-1.35.2.72/c/src/api/ltkc_win32/Definitions/LLRP.org/LLRPOrgExampleDef.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
 -  Copyright 2011 Trimble, Inc.

 -  Copyright 2006, 2007 EPCglobal Inc.
 -     (The proprietary text of EPCglobal Inc. included herein is not
 -      a Contribution to the work. The right to use the proprietary
 -      text is limited to reproduction and display thereof within
 -      the work.)

 -  Licensed under the Apache License, Version 2.0 (the "License");
 -  you may not use this file except in compliance with the License.
 -  You may obtain a copy of the License at
 -
 -      http://www.apache.org/licenses/LICENSE-2.0
 -
 -  Unless required by applicable law or agreed to in writing, software
 -  distributed under the License is distributed on an "AS IS" BASIS,
 -  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 -  See the License for the specific language governing permissions and
 -  limitations under the License.
 -
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
 -->

<llrpdef
	xmlns="http://www.llrp.org/ltk/schema/core/encoding/binary/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:h="http://www.w3.org/1999/xhtml"
        xsi:schemaLocation="
		  http://www.llrp.org/ltk/schema/core/encoding/binary/1.0
		  http://www.llrp.org/ltk/schema/core/encoding/binary/1.0/llrpdef.xsd"
>

<vendorDefinition       name="thingmagic" vendorID="26554" />
<namespaceDefinition    prefix="thingmagic"
	URI="http://www.thingmagic.com/ltk/schema/extension/xml/1.0/"
                        schemaLocation="http://www.thingmagic.com/ltk/schema/extension/xml/1.0/thingmagic.xsd" />
<customMessageDefinition        name="THINGMAGIC_CONTROL_REQUEST_POWER_CYCLE_READER"
                                vendor="thingmagic" subtype="1"
                                namespace="thingmagic"
				responseType="THINGMAGIC_CONTROL_RESPONSE_POWER_CYCLE_READER">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>power cycle the ThingMagic reader</h:p>
    </description>
  </annotation>
  <field type="u32" name="MagicNumber"/>
  <field type="u1" name="BootToSafeMode"/> 
  <reserved bitCount="7"/> 
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_RESPONSE_POWER_CYCLE_READER"
                                vendor="thingmagic" subtype="2"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Response message to power cycle the ThingMagic reader request</h:p>
    </description>
  </annotation>
  <parameter  repeat="1"      type="LLRPStatus"/>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>


<customMessageDefinition        name="THINGMAGIC_CONTROL_REQUEST_RESET_STATISTICS"
                                vendor="thingmagic" subtype="3"
                                namespace="thingmagic"
                                responseType="THINGMAGIC_CONTROL_RESPONSE_RESET_STATISTICS">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Reset reader statistics</h:p>
    </description>
  </annotation>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_RESPONSE_RESET_STATISTICS"
                                vendor="thingmagic" subtype="4"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Response message to power cycle the ThingMagic reader request</h:p>
    </description>
  </annotation>
  <parameter  repeat="1"      type="LLRPStatus"/>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>


<customMessageDefinition        name="THINGMAGIC_CONTROL_REQUEST_GET_RESET_TIME"
                                vendor="thingmagic" subtype="5"
                                namespace="thingmagic"
                                responseType="THINGMAGIC_CONTROL_RESPONSE_GET_RESET_TIME">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Time stamp when reader statistics are reset</h:p>
    </description>
  </annotation>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_RESPONSE_GET_RESET_TIME"
                                vendor="thingmagic" subtype="6"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Response message to Get reset statistics time stamp request </h:p>
    </description>
  </annotation>
  <parameter  repeat="1"      type="LLRPStatus"/>
  <field type="u64" name="Microseconds" format="Datetime"/> 
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>


<customMessageDefinition        name="THINGMAGIC_CONTROL_REQUEST_GET_ANTENNA_STATS"
                                vendor="thingmagic" subtype="7"
                                namespace="thingmagic"
                                responseType="THINGMAGIC_CONTROL_RESPONSE_GET_ANTENNA_STATS">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Request to get Reader Antenna statistics.</h:p>
    </description>
  </annotation>
  <field type="u16" name="AntennaID"/>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_RESPONSE_GET_ANTENNA_STATS"
                                vendor="thingmagic" subtype="8"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Response message to get reader antenna statistics request</h:p>
    </description>
  </annotation>
  <parameter  repeat="1"      type="LLRPStatus"/>
  <field      type="u32"      name="TagsIdentified"/>
  <field      type="u32"      name="TagsNotIdentified"/>
  <field      type="u32"      name="MemoryReadFailures"/>
  <field      type="u32"      name="WriteOperations"/>
  <field      type="u32"      name="WriteFailures"/>
  <field      type="u32"      name="KillOperations"/>
  <field      type="u32"      name="KillFailures"/>
  <field      type="u32"      name="EraseOperations"/>
  <field      type="u32"      name="EraseFailures"/>
  <field      type="u32"      name="LockOperations"/>
  <field      type="u32"      name="LockFailures"/>
  <field      type="u32"      name="NoiseLevel"/>
  <field      type="u32"      name="TimeEnergised"/>
  <field      type="u32"      name="PowerLevel"/>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_REQUEST_GET_READER_STATUS"
                                vendor="thingmagic" subtype="11"
                                namespace="thingmagic"
                                responseType="THINGMAGIC_CONTROL_RESPONSE_GET_READER_STATUS">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Request to get Reader device status.</h:p>
    </description>
  </annotation>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customMessageDefinition        name="THINGMAGIC_CONTROL_RESPONSE_GET_READER_STATUS"
                                vendor="thingmagic" subtype="12"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>Response message to power cycle the ThingMagic reader request</h:p>
    </description>
  </annotation>
  <parameter  repeat="1"      type="LLRPStatus"/>
  <field      type="u8"   	name="ReaderDeviceOperatingStatus"
			 	enumeration="ThingMagicReaderOperatingStatus"/>
  <parameter  repeat="0-N"    type="Custom"/>
</customMessageDefinition>

<customEnumerationDefinition    name="ThingMagicReaderOperatingStatus"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>An enumeration of ThingMagic Reader Device operating status</h:p>
    </description>
  </annotation>
  <entry     value="0"      name="IDLE"/>
  <entry     value="1"      name="RUNNING"/>
  <entry     value="2"      name="ERROR"/>
</customEnumerationDefinition>

<customParameterDefinition      name="ThingMagicDeviceControlCapabilities"
                                vendor="thingmagic" subtype="1"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description>
      <h:p>This parameter fills in the control plane capabilities that are specific to a thingmagic reader. </h:p>
    </description>
  </annotation>
  <field     	type="u8"   	name="RequestedData"
			 	enumeration="ThingMagicControlCapabilities"/>
  <parameter    repeat="0-N"    type="Custom"/>
  <allowedIn 	repeat="0-1"    type="GET_READER_CAPABILITIES"/>
</customParameterDefinition>

<customEnumerationDefinition    name="ThingMagicControlCapabilities"
                                namespace="thingmagic">
  <annotation>
    <documentation>
    </documentation>
    <description copyright="">
      <h:p>An enumeration of ThingMagic Control plane capabilities</h:p>
    </description>
  </annotation>
  <entry     value="0"      name="All"/>
  <entry     value="1"      name="DeviceInformationCapabilities"/>
